### ISSUE TITLE
program update lag

### ISSUE THREAD

**Issue by jichang22** [PHACDataHub/dhis2#3]
There is definitely a lag in applying the program updates to the program itself in real time - this delay can be between 5 mins to 48 hours, and persists despite clearing the cache and browser history.

**Comment by jichang22** [comment]
tracker capture program

**Comment by jichang22** [comment]
update vm to new version of dhis2 (core-dev:2.40), advice client to test it out to see if the problem persists

**Comment by raa7mad** [comment]
Program rules have been added to the new version of dhis2. Some rules work, others don't. I initially thought it was a lag issue as those that work have the same syntax as those that do not work, but it has been over a week since i wrote some of those rules and they haven't appeared in the program so it may not be a lag issue in this instance, rather something to do with the program rules.

**Comment by jichang22** [comment]
need to be able to clear cache, moving to use edge as the web browser
